/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.foodordering;

/**
 *
 * @author theme
 */
public class OrderViewForm extends javax.swing.JFrame {

    /**
     * Creates new form OrderViewForm
     */
    public OrderViewForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eateryName = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        drink1 = new javax.swing.JButton();
        drink2 = new javax.swing.JButton();
        drink3 = new javax.swing.JButton();
        drink4 = new javax.swing.JButton();
        drinks = new javax.swing.JLabel();
        drinks1 = new javax.swing.JLabel();
        app1 = new javax.swing.JButton();
        app2 = new javax.swing.JButton();
        app3 = new javax.swing.JButton();
        app4 = new javax.swing.JButton();
        drinks2 = new javax.swing.JLabel();
        main1 = new javax.swing.JButton();
        main2 = new javax.swing.JButton();
        main3 = new javax.swing.JButton();
        main4 = new javax.swing.JButton();
        drinks3 = new javax.swing.JLabel();
        side1 = new javax.swing.JButton();
        side2 = new javax.swing.JButton();
        side3 = new javax.swing.JButton();
        side4 = new javax.swing.JButton();
        drinks4 = new javax.swing.JLabel();
        dessert1 = new javax.swing.JButton();
        dessert2 = new javax.swing.JButton();
        dessert3 = new javax.swing.JButton();
        dessert4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eatery:");

        eateryName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eateryName.setText("EateryName");
        eateryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eateryNameActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Menu");
        jLabel2.setToolTipText("");

        drink1.setText("Drink_1");

        drink2.setText("Drink_2");

        drink3.setText("Drink_3");

        drink4.setText("Drink_4");

        drinks.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        drinks.setText("Drinks");

        drinks1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        drinks1.setText("Appetizers");

        app1.setText("App_1");

        app2.setText("App_2");

        app3.setText("App_3");

        app4.setText("App_4");

        drinks2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        drinks2.setText("Mains");

        main1.setText("Main_1");

        main2.setText("Main_2");

        main3.setText("Main_3");

        main4.setText("Main_4");

        drinks3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        drinks3.setText("Sides");

        side1.setText("Side_1");

        side2.setText("Side_2");

        side3.setText("Side_3");

        side4.setText("Side_4");

        drinks4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        drinks4.setText("Desserts");

        dessert1.setText("Dessert_1");

        dessert2.setText("Dessert_2");

        dessert3.setText("Dessert_3");

        dessert4.setText("Dessert_4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinks)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(drink1)
                        .addGap(18, 18, 18)
                        .addComponent(drink2)
                        .addGap(18, 18, 18)
                        .addComponent(drink3)
                        .addGap(18, 18, 18)
                        .addComponent(drink4))
                    .addComponent(drinks1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(app1)
                        .addGap(18, 18, 18)
                        .addComponent(app2)
                        .addGap(18, 18, 18)
                        .addComponent(app3)
                        .addGap(18, 18, 18)
                        .addComponent(app4))
                    .addComponent(drinks2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(main1)
                        .addGap(18, 18, 18)
                        .addComponent(main2)
                        .addGap(18, 18, 18)
                        .addComponent(main3)
                        .addGap(18, 18, 18)
                        .addComponent(main4))
                    .addComponent(drinks3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(side1)
                        .addGap(18, 18, 18)
                        .addComponent(side2)
                        .addGap(18, 18, 18)
                        .addComponent(side3)
                        .addGap(18, 18, 18)
                        .addComponent(side4))
                    .addComponent(drinks4)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dessert1)
                        .addGap(18, 18, 18)
                        .addComponent(dessert2)
                        .addGap(18, 18, 18)
                        .addComponent(dessert3)
                        .addGap(18, 18, 18)
                        .addComponent(dessert4)))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(drinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(drink1)
                    .addComponent(drink2)
                    .addComponent(drink3)
                    .addComponent(drink4))
                .addGap(31, 31, 31)
                .addComponent(drinks1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(app1)
                    .addComponent(app2)
                    .addComponent(app3)
                    .addComponent(app4))
                .addGap(31, 31, 31)
                .addComponent(drinks2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(main1)
                    .addComponent(main2)
                    .addComponent(main3)
                    .addComponent(main4))
                .addGap(31, 31, 31)
                .addComponent(drinks3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(side1)
                    .addComponent(side2)
                    .addComponent(side3)
                    .addComponent(side4))
                .addGap(31, 31, 31)
                .addComponent(drinks4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dessert1)
                    .addComponent(dessert2)
                    .addComponent(dessert3)
                    .addComponent(dessert4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eateryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(eateryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eateryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eateryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eateryNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderViewForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton app1;
    private javax.swing.JButton app2;
    private javax.swing.JButton app3;
    private javax.swing.JButton app4;
    private javax.swing.JButton dessert1;
    private javax.swing.JButton dessert2;
    private javax.swing.JButton dessert3;
    private javax.swing.JButton dessert4;
    private javax.swing.JButton drink1;
    private javax.swing.JButton drink2;
    private javax.swing.JButton drink3;
    private javax.swing.JButton drink4;
    private javax.swing.JLabel drinks;
    private javax.swing.JLabel drinks1;
    private javax.swing.JLabel drinks2;
    private javax.swing.JLabel drinks3;
    private javax.swing.JLabel drinks4;
    private javax.swing.JTextField eateryName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton main1;
    private javax.swing.JButton main2;
    private javax.swing.JButton main3;
    private javax.swing.JButton main4;
    private javax.swing.JButton side1;
    private javax.swing.JButton side2;
    private javax.swing.JButton side3;
    private javax.swing.JButton side4;
    // End of variables declaration//GEN-END:variables
}
