package view.foodordering;

import controller.foodordering.FoodController;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import model.foodordering.MenuItem;
import javax.swing.ImageIcon;

/**
 * Order Confirmation View Form. User uses this page to complete order pickup,
 * view details of the order, and mark an order as picked up.
 * @author theme
 */
public class OrderConfirmationViewForm extends javax.swing.JFrame implements ActionListener {
    
    private FoodController cntl;

    /**
     * Creates new form OrderConfirmationViewForm. Initializes the components for 
     * this view. Sets the controller. View is created with information from the current
     * order details that were selected in OrderViewForm. 
     * @param cntl
     */
    public OrderConfirmationViewForm(FoodController cntl) {
        initComponents();
        this.cntl = cntl;
        this.cntl.setConfirmationView(this);
        populateConfirmationForm();
        setActionListeners();
        setLocationRelativeTo(null);
        this.setVisible(false);      
    }
    
    /**
     * Helper method to populate the confirmation form with details from the 
     * current order. 
     */
    private void populateConfirmationForm(){
        DefaultTableModel tableModel = (DefaultTableModel) orderSummaryTable.getModel();
        ImageIcon barcodeIcon = new ImageIcon(getClass().getResource("/images/barcode-306926_1280.png"));
        orderNumber.setText(cntl.getOrderNumber());
        pickupTime.setText(cntl.getPickupTime());
        totalCost.setText("$" + String.format("%.2f", cntl.getTotal()));
        
        for (MenuItem item : cntl.getOrderItems()){
            tableModel.addRow(new Object[] {item.getItemName(), item.getPrice(), item.getQuantity()});
        }
        
        Image image = barcodeIcon.getImage();
        Image scaledImage = image.getScaledInstance(200, 50, Image.SCALE_SMOOTH); 
        ImageIcon scaledBarcodeIcon = new ImageIcon(scaledImage); 
        barCode.setIcon(scaledBarcodeIcon);
        barCode.setHorizontalAlignment(SwingConstants.CENTER);
        orderSummaryTable.getTableHeader().setResizingAllowed(false);
        orderSummaryTable.getTableHeader().setReorderingAllowed(false);
        
    }
    
    /**
     * Clears the order confirmation view. To be used when an order is marked as complete
     * and a new order can be started. Resets the view so order confirmation can 
     * not be displayed after pickup. 
     */
    public void clearOrderConfirmationView(){
        orderNumber.setText("");
        pickupTime.setText("");
        totalCost.setText("$0.00");
        
        DefaultTableModel tableModel = (DefaultTableModel) orderSummaryTable.getModel();
        tableModel.setRowCount(0); // Remove all rows from the table
    }
    
    /**
     * Sets action listeners
     */
    private void setActionListeners(){
        markAsComplete.addActionListener(this);
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        //Marks the order as complete. Clears the confirmation form and hides the form.
        //resets order view for new order
        if (e.getSource() == markAsComplete){
            cntl.markedOrderAsPickedUp();
            clearOrderConfirmationView();
            this.setVisible(false);
            cntl.setOrderView(new OrderViewForm(cntl));
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        orderConfirmation = new javax.swing.JLabel();
        orderNumber = new javax.swing.JLabel();
        orderNumberLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        orderSummaryTable = new javax.swing.JTable();
        totalLabel = new javax.swing.JLabel();
        totalCost = new javax.swing.JLabel();
        pickupTime = new javax.swing.JLabel();
        pickupTimeLabel = new javax.swing.JLabel();
        markAsComplete = new javax.swing.JButton();
        barCode = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("WallyLand - Order Confirmation");
        setBackground(new java.awt.Color(58, 115, 169));
        setIconImage(new ImageIcon(getClass().getResource("/images/theme-park.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(227, 236, 241));

        orderConfirmation.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        orderConfirmation.setText("Order Confirmation");

        orderNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderNumber.setText("123456");

        orderNumberLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        orderNumberLabel.setText("Order Number:");

        orderSummaryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(orderSummaryTable);

        totalLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalLabel.setText("Total:");

        totalCost.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        totalCost.setText("123456");

        pickupTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pickupTime.setText("10:00 AM");

        pickupTimeLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pickupTimeLabel.setText("Pickup Time:");

        markAsComplete.setText("Mark As Complete");

        jLabel1.setText("Show this Bar Code to Cashier at Pick Up");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barCode, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pickupTimeLabel)
                            .addComponent(totalLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pickupTime)
                            .addComponent(totalCost))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(markAsComplete)
                        .addGap(36, 36, 36))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(orderNumberLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orderNumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(orderConfirmation)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(orderConfirmation)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(orderNumberLabel)
                    .addComponent(orderNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(barCode, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalCost)
                            .addComponent(totalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pickupTimeLabel)
                            .addComponent(pickupTime)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(markAsComplete)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrderConfirmationViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrderConfirmationViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrderConfirmationViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrderConfirmationViewForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                FoodController cntl = new FoodController();
//                new OrderConfirmationViewForm(cntl).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton markAsComplete;
    private javax.swing.JLabel orderConfirmation;
    private javax.swing.JLabel orderNumber;
    private javax.swing.JLabel orderNumberLabel;
    private javax.swing.JTable orderSummaryTable;
    private javax.swing.JLabel pickupTime;
    private javax.swing.JLabel pickupTimeLabel;
    private javax.swing.JLabel totalCost;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables

    
}
